"""Generate the dependency-free Pokelike Guide static site."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "public"
GA_ID = "G-B7HK8JPQPS"

TOP_AD = """
<aside class="top-ad" aria-label="Advertisement"><span>Advertisement</span><script async="async" data-cfasync="false" src="https://pl31325133.profitableratecpmnetwork.com/b87b668a48c79cbabf012f126c397ec0/invoke.js"></script><div id="container-b87b668a48c79cbabf012f126c397ec0"></div></aside>
"""

AD_SCRIPTS = """
<script src="https://pl31325131.profitableratecpmnetwork.com/cf/d1/a6/cfd1a6892f5f97772342d8e6891161e1.js"></script><script src="https://pl31325134.profitableratecpmnetwork.com/df/53/23/df5323aa1e62585a69e5b0b0c2ae0903.js"></script>
"""

NAV = """
<a href="/pokesort/">Pokesort</a><a href="/regions/">Regions</a><a href="/traits/">Traits</a><a href="/battle-tower/">Battle Tower</a><a href="/guides/getting-started/">Beginner Guide</a><a href="/community/">Community</a>
"""

FOOTER = """
<footer><div class="footer-grid"><div><a class="logo" href="/"><span>PG</span> Pokelike Guide</a><p>Independent, player-made guides for Pokelike.xyz. Facts are checked against playable builds and clearly dated.</p></div><div><strong>Popular</strong><a href="/pokesort/">Pokesort guide</a><a href="/regions/johto/">Johto guide</a><a href="/traits/">All traits</a></div><div><strong>Site</strong><a href="/guides/getting-started/">Getting started</a><a href="/community/">Reddit sources</a><a href="/privacy/">Privacy</a><a href="mailto:hello@pokelikeguide.cc">Corrections</a></div></div><div class="legal">© 2026 Pokelike Guide. Unofficial fan resource; not affiliated with Pokelike.xyz, Nintendo, Game Freak, or The Pokémon Company.</div></footer>
"""


def page(title: str, description: str, canonical: str, body: str, *, schema_type: str = "Article") -> str:
    return f"""<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title><meta name="description" content="{description}"><meta name="theme-color" content="#102f28">
<link rel="canonical" href="https://pokelikeguide.cc{canonical}"><meta property="og:type" content="website"><meta property="og:title" content="{title}"><meta property="og:description" content="{description}"><meta property="og:url" content="https://pokelikeguide.cc{canonical}">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Fredoka:wght@500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/styles.css">
<script type="application/ld+json">{{"@context":"https://schema.org","@type":"{schema_type}","headline":"{title}","url":"https://pokelikeguide.cc{canonical}","isPartOf":{{"@type":"WebSite","name":"Pokelike Guide","url":"https://pokelikeguide.cc/"}}}}</script>
<!-- Google tag (gtag.js) --><script async src="https://www.googletagmanager.com/gtag/js?id={GA_ID}"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){{dataLayer.push(arguments)}}gtag('js',new Date());gtag('config','{GA_ID}');</script></head>
<body><header><a class="logo" href="/"><span>PG</span> Pokelike Guide</a><nav>{NAV}</nav><button class="menu" aria-label="Open navigation" aria-expanded="false">Menu</button></header>
{TOP_AD}<main>{body}</main>{FOOTER}<script src="/script.js"></script>{AD_SCRIPTS}</body></html>"""


def write(url: str, html: str) -> None:
    path = PUBLIC / (url.strip("/") or ".") / "index.html"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8")


home = """
<section class="hero"><div><p class="kicker">Independent Pokelike.xyz companion</p><h1>Make every run<br><em>go further.</em></h1><p class="lede">Fast answers for Pokesort, region progression, type traits, and Battle Tower—without burying the useful part.</p><div class="actions"><a class="primary" href="/pokesort/">Open Pokesort guide →</a><a class="secondary" href="/guides/getting-started/">Start a new run</a></div><p class="proof"><b>Current coverage:</b> Kanto through Unova · Normal · Nuzlocke · Battle Tower</p></div><div class="run-card"><div class="run-top"><span>RUN COMPANION</span><b>LIVE GUIDE</b></div><div class="route"><i>●</i><i>?</i><i>⚔</i><i>★</i></div><h2>Choose the smarter path.</h2><p>Check the matchup, understand the trait, and know what comes next before committing to a node.</p><div class="mini-stats"><span><b>5</b> regions</span><span><b>3</b> modes</span><span><b>1</b> clear answer</span></div></div></section>
<section class="signal"><span>Popular player guides</span><a href="/pokesort/">Pokesort #76 answer</a><a href="/regions/johto/">Pokelike Johto guide</a><a href="/traits/">Pokelike traits explained</a></section>
<section class="section"><p class="kicker orange">Updated September 15</p><div class="split-title"><h2>Today’s Pokésort #76<br>is verified.</h2><p>See the six Pokémon in order, five connecting relationships, spoiler-free hints, and a dated archive page for the September 15 puzzle.</p></div><a class="feature-card daily" href="/pokesort/"><div><span class="badge">ANSWER AVAILABLE</span><h3>Pokésort #76</h3><p>Kakuna → Mienshao → Kingdra → Shellos → Snorunt → Ledian</p></div><span class="big-arrow">→</span></a></section>
<section class="section soft"><p class="kicker">Pick a region</p><div class="split-title"><h2>Guides for every<br>campaign.</h2><a class="underlink" href="/regions/">Compare all regions →</a></div><div class="region-grid"><a href="/regions/kanto/"><b>01</b><h3>Kanto</h3><p>Gym route and Elite Four prep.</p></a><a href="/regions/johto/"><b>02</b><h3>Johto</h3><p>Strategy and Lance preparation.</p></a><a href="/regions/hoenn/"><b>03</b><h3>Hoenn</h3><p>Aqua, Magma, Wallace, and Steven.</p></a><a href="/regions/sinnoh/"><b>04</b><h3>Sinnoh</h3><p>Unlock path and Cynthia prep.</p></a><a href="/regions/unova/"><b>05</b><h3>Unova</h3><p>Team Plasma, Ghetsis, and Alder.</p></a></div></section>
<section class="section"><p class="kicker orange">Build with intent</p><div class="split-title"><h2>Understand the systems<br>that decide a run.</h2></div><div class="guide-grid"><a href="/traits/"><span>TYPE SYNERGY</span><h3>Pokelike Traits Explained</h3><p>How same-type team members activate tiered bonuses—and why shiny team members matter in Tower planning.</p><b>Read trait guide →</b></a><a href="/battle-tower/"><span>ENDLESS MODE</span><h3>Battle Tower Guide</h3><p>Understand stages, regional teams, manual versus auto play, and the choices that carry between fights.</p><b>Enter the tower →</b></a><a href="/guides/getting-started/"><span>FIRST RUN</span><h3>Beginner Guide</h3><p>Pick a mode, read the branching map, protect the lead slot, and prepare for eight gyms and the league.</p><b>Start here →</b></a></div></section>
<section class="notice"><div><p class="kicker">Verification policy</p><h2>Useful beats inflated.</h2></div><p>We do not publish guessed daily answers or pretend a community fork is the live game. Every changing fact is dated; uncertain details are labeled and rechecked after updates.</p></section>
"""
write("/", page("Pokelike Guide & Wiki — Pokesort, Traits and Region Guides", "Independent Pokelike.xyz guide with Pokesort help, Kanto through Unova walkthroughs, traits, Battle Tower strategy, and beginner tips.", "/", home, schema_type="WebSite"))

pokesort = """
<section class="article-hero"><nav class="crumb"><a href="/">Home</a> / Pokésort</nav><p class="kicker orange">September 15, 2026 · Puzzle #76</p><h1>Pokelike Pokésort<br>Answer Today</h1><p class="lede">Today’s six-Pokémon chain and all five relationships, with the answer hidden behind a spoiler control.</p><div class="status verified"><span>CURRENT DAILY ANSWER</span><b>Pokésort #76 verified</b><p>Game date: September 15, 2026. This answer is for the Pokelike.xyz minigame, not Pokesort.com or Pokesort.org.</p></div></section>
<article class="article"><h2>Spoiler-free hints</h2><ol class="hint-list"><li>Start with a Generation I Pokémon that evolves into Beedrill.</li><li>The middle pair share one type even though their second types differ.</li><li>The last link is decided by type effectiveness.</li></ol><details class="answer-reveal"><summary>Reveal the Pokésort #76 answer</summary><div class="answer-body"><p class="answer-date">SEPTEMBER 15, 2026 · #76</p><div class="answer-chain"><span><b>Kakuna</b><small>铁壳蛹</small></span><i>Earlier generation</i><span><b>Mienshao</b><small>师父鼬</small></span><i>Later generation</i><span><b>Kingdra</b><small>刺龙王</small></span><i>Same type</i><span><b>Shellos</b><small>无壳海兔</small></span><i>Later generation</i><span><b>Snorunt</b><small>雪童子</small></span><i>Type advantage</i><span><b>Ledian</b><small>安瓢虫</small></span></div></div></details><h2>Answer explained</h2><ol><li><b>Kakuna → Mienshao: earlier generation.</b> Kakuna debuted before Mienshao.</li><li><b>Mienshao → Kingdra: later generation.</b> Mienshao debuted after Kingdra.</li><li><b>Kingdra → Shellos: same type.</b> Both share the Water type.</li><li><b>Shellos → Snorunt: later generation.</b> Shellos debuted after Snorunt.</li><li><b>Snorunt → Ledian: type advantage.</b> Snorunt’s Ice typing is super effective against Ledian’s Flying typing.</li></ol><p><a class="underlink" href="/pokesort/2026-09-15/">Open the permanent Pokésort #76 archive page →</a></p><h2>Community sources</h2><p>Reddit has recurring Pokésort hints and spoiler discussions. Use newest-first sorting so an older board is not mistaken for today’s answer.</p><div class="source-links"><a href="https://www.reddit.com/r/Pokelike/search/?q=pokesort&amp;restrict_sr=1&amp;sort=new" rel="nofollow noopener">Search recent r/Pokelike posts ↗</a><a href="https://www.reddit.com/r/Pokesort/new/" rel="nofollow noopener">Open newest r/Pokesort posts ↗</a></div><aside><strong>Search-result warning</strong><p>Pokesort.com and Pokesort.org are separate puzzle sites. Their daily answers must not be substituted for Pokelike Pokésort #76.</p></aside></article>
"""
write("/pokesort/", page("Pokelike Pokésort Answer Today #76 — September 15, 2026", "Pokelike Pokésort #76 answer for September 15, 2026: Kakuna, Mienshao, Kingdra, Shellos, Snorunt, and Ledian, with all relationships explained.", "/pokesort/", pokesort))

pokesort_76 = """
<section class="article-hero"><nav class="crumb"><a href="/">Home</a> / <a href="/pokesort/">Pokésort</a> / #76</nav><p class="kicker orange">Daily answer archive</p><h1>Pokésort #76 Answer<br>for September 15, 2026</h1><p class="lede">The permanent archive for today’s Pokelike.xyz Pokésort chain.</p></section><article class="article"><h2>Pokésort #76 solution</h2><div class="answer-body standalone"><p class="answer-date">FROM LEFT TO RIGHT</p><div class="answer-chain"><span><b>Kakuna</b><small>铁壳蛹</small></span><i>Earlier generation</i><span><b>Mienshao</b><small>师父鼬</small></span><i>Later generation</i><span><b>Kingdra</b><small>刺龙王</small></span><i>Same type</i><span><b>Shellos</b><small>无壳海兔</small></span><i>Later generation</i><span><b>Snorunt</b><small>雪童子</small></span><i>Type advantage</i><span><b>Ledian</b><small>安瓢虫</small></span></div></div><h2>Relationship sequence</h2><p><strong>Earlier generation → Later generation → Same type → Later generation → Type advantage.</strong></p><p>Kingdra and Shellos share Water typing. The final relationship works because Ice is super effective against Flying.</p><p><a class="underlink" href="/pokesort/">Return to the current Pokésort answer →</a></p></article>
"""
write("/pokesort/2026-09-15/", page("Pokésort #76 Answer — September 15, 2026 | Pokelike", "Pokelike Pokésort #76 solution for September 15, 2026, with the six Pokémon in order and all five relationships.", "/pokesort/2026-09-15/", pokesort_76))

getting = """
<section class="article-hero"><nav class="crumb"><a href="/">Home</a> / Guides / Getting Started</nav><p class="kicker orange">First run</p><h1>Pokelike Beginner Guide</h1><p class="lede">Pokelike is a browser-based Pokémon roguelike built around irreversible route choices, team management, eight gyms, and a final league.</p></section><article class="article"><h2>The run in one minute</h2><p>Choose a generation, select Normal or Nuzlocke, and pick a starter. Each map is a branching series of reachable nodes. Battles, catches, items, trades, events, Pokémon Centers, and Move Tutors compete for your route; each map ends with a Gym Leader, and the final map leads to the Elite Four and Champion.</p><h2>Normal or Nuzlocke?</h2><div class="compare"><div><h3>Normal</h3><p>Designed for learning. Depending on the chosen wipe rule, a full-team faint can restart the area or end the run.</p></div><div><h3>Nuzlocke</h3><p>Hardcore mode. A fainted team member is normally lost permanently, and a full wipe ends the run.</p></div></div><h2>Five decisions that matter</h2><ol><li><b>Read the next layers.</b> A reachable node closes alternatives on that layer, so look ahead before clicking.</li><li><b>Protect team coverage.</b> Catching raw power is less useful if several members share the same weakness.</li><li><b>Plan healing.</b> A Pokémon Center can restore the team, but the route needed to reach it has an opportunity cost.</li><li><b>Respect speed and immunities.</b> Faster Pokémon act first; an immune target takes no damage from that move type.</li><li><b>Prepare before the boss.</b> Gym and league teams are the tests that determine progression.</li></ol><aside><strong>Version note</strong><p>This overview reflects functionality documented in recent public Pokelike forks. Exact balance values may change in the live build; changing facts are not presented here without a verification date.</p></aside></article>
"""
write("/guides/getting-started/", page("Pokelike Beginner Guide — How to Start and Survive a Run", "A concise Pokelike beginner guide covering modes, branching maps, catches, healing, team coverage, gyms, and Nuzlocke risk.", "/guides/getting-started/", getting))

regions = [
    ("kanto", "Kanto", "Generation I · #001–151", "Eight Kanto Gym Leaders lead into the Kanto Elite Four and Champion.", "Kanto searches specifically include Elite Four, Elite 4 order, E4, tips, and guide intent."),
    ("johto", "Johto", "Generation II · #001–251", "Eight Johto Gym Leaders lead into the Johto Elite Four and Lance.", "Johto has direct guide, strategy, tips, and Reddit search demand."),
    ("hoenn", "Hoenn", "Generation III · #252–386 catchable", "The route features Hoenn leaders, Team Aqua or Team Magma ambushes, the Elite Four, and Champion Steven.", "Hoenn guide and tips appear in current search suggestions."),
    ("sinnoh", "Sinnoh", "Generation IV · #387–493 catchable", "Sinnoh unlocks after a Hoenn win in the documented build and culminates in the Elite Four and Cynthia.", "Sinnoh Tower and Reddit queries appear in current search suggestions."),
    ("unova", "Unova", "Generation V · #494–649 catchable", "Unova unlocks after a Sinnoh win in the documented build and includes Team Plasma encounters before Alder's league.", "Unova, Unova Battle Tower, and Unova Reddit are established search suggestions."),
]
cards = "".join(f'<a href="/regions/{slug}/"><b>{label}</b><span>{subtitle}</span><p>{summary}</p></a>' for slug,label,subtitle,summary,_ in regions)
hub = f'<section class="article-hero"><nav class="crumb"><a href="/">Home</a> / Regions</nav><p class="kicker orange">Campaign routes</p><h1>Pokelike Region Guides</h1><p class="lede">Choose a generation and prepare for its gym route, rival encounters, league, and unlock path.</p></section><section class="section"><div class="region-list">{cards}</div></section>'
write("/regions/", page("Pokelike Region Guides — Kanto, Johto, Hoenn, Sinnoh & Unova", "Pokelike region guide hub for Kanto, Johto, Hoenn, Sinnoh, and Unova campaigns, including progression and league preparation.", "/regions/", hub))
for slug, label, subtitle, summary, demand in regions:
    body = f'<section class="article-hero"><nav class="crumb"><a href="/">Home</a> / <a href="/regions/">Regions</a> / {label}</nav><p class="kicker orange">{subtitle}</p><h1>Pokelike {label} Guide</h1><p class="lede">{summary}</p></section><article class="article"><h2>What this campaign includes</h2><p>{summary} The run uses the same core branching-map decisions: decide between battles, catches, items, trades, events, healing, and move improvements before committing to a path.</p><h2>Search demand for this guide</h2><p>{demand} This page consolidates that intent rather than creating several short, overlapping pages.</p><h2>Preparation checklist</h2><ul><li>Cover the major type weaknesses represented by your current route and upcoming boss.</li><li>Keep the lead slot healthy and review speed before entering a mandatory fight.</li><li>Use healing and Move Tutor opportunities before the league rather than carrying unused resources.</li><li>Check the current game version before relying on fixed balance or encounter data.</li></ul><aside><strong>Accuracy status</strong><p>Campaign structure is based on recent public rule implementations. Exact teams, levels, and rewards require live-build verification before publication and are intentionally not invented here.</p></aside></article>'
    write(f"/regions/{slug}/", page(f"Pokelike {label} Guide — Strategy, Progression & League", f"Pokelike {label} guide covering campaign progression, route planning, team preparation, and the {label} league.", f"/regions/{slug}/", body))

traits = """
<section class="article-hero"><nav class="crumb"><a href="/">Home</a> / Traits</nav><p class="kicker orange">Team synergy</p><h1>Pokelike Traits Explained</h1><p class="lede">Type traits are a core Battle Tower system: stacking same-type team members unlocks tiered bonuses, while shiny members contribute additional trait value.</p></section><article class="article"><div class="source-note"><span>COMMUNITY-SOURCED</span><p>This strategy section incorporates the recurring team-building discussion in the r/Pokelike <a href="https://www.reddit.com/r/Pokelike/comments/1t82gmz/tips_and_tricks/" rel="nofollow noopener">Tips and Tricks thread</a>. Mechanics that can change remain labeled rather than converted into unsupported percentages.</p></div><h2>How traits affect team building</h2><p>Community discussion focuses on the first meaningful breakpoint: two Pokémon sharing a type can activate a Tier 1 bonus. That makes a catch or trade valuable for more than its individual stats. Shiny Pokémon also contribute extra trait value in the documented Tower rules, so a shiny can change which breakpoint your team reaches.</p><div class="steps"><div><b>01</b><h3>Count shared types</h3><p>Check both types on every team member. A dual-type Pokémon may advance two different synergies at once.</p></div><div><b>02</b><h3>Price the breakpoint</h3><p>Do not replace a good counter merely to light up a trait. Compare the new passive bonus with the coverage and speed you lose.</p></div><div><b>03</b><h3>Scout the enemy theme</h3><p>Enemy teams can have traits too. Use the Tower preview to avoid stacking into a matchup that directly punishes your plan.</p></div></div><h2>Community-backed planning rules</h2><ul><li><b>Build one reliable core first.</b> Reaching a useful low-tier synergy is safer than chasing several incomplete traits.</li><li><b>Shiny value is strategic.</b> Evaluate the extra trait contribution before replacing a shiny with a small raw-stat upgrade.</li><li><b>Keep an off-type answer.</b> Monotype stacking can amplify one shared weakness; retain a lead or switch-in that covers it.</li><li><b>Recalculate after every catch and trade.</b> Dual typings can move more than one trait threshold.</li></ul><h2>What still needs live verification</h2><p>Exact tier thresholds, effect percentages, and balance changes are not filled from memory. The next database release should record the game version, threshold, effect, and last-tested date for every trait.</p></article>
"""
write("/traits/", page("Pokelike Traits Explained — Type Synergy & Best Team Planning", "Understand Pokelike traits, type stacking, shiny trait value, tier thresholds, and Battle Tower team synergy.", "/traits/", traits))

tower = """
<section class="article-hero"><nav class="crumb"><a href="/">Home</a> / Battle Tower</nav><p class="kicker orange">Endless challenge</p><h1>Pokelike Battle Tower Guide</h1><p class="lede">Battle Tower is a separate endless challenge built around stages, regional opponents, team management, type traits, and score.</p></section><article class="article"><div class="source-note"><span>REDDIT STRATEGY SIGNAL</span><p>The r/Pokelike <a href="https://www.reddit.com/r/Pokelike/comments/1t82gmz/tips_and_tricks/" rel="nofollow noopener">Tips and Tricks discussion</a> repeatedly connects Tower success with trait stacking, shiny contribution, item choices, and safer Nuzlocke-style planning.</p></div><h2>What is different in the Tower?</h2><p>Public rule implementations describe a stage-based mode that can be played manually or resolved automatically. Type traits remain active, opponent themes change by region, and progression is measured by how deep the run reaches. That rewards a team that handles many fights, not a one-battle gimmick.</p><h2>Build around repeatable strength</h2><ul><li><b>Coverage:</b> avoid a team that folds to one common attacking type, even when stacking that type activates a stronger trait.</li><li><b>Trait efficiency:</b> count dual types and shiny contribution before accepting a catch or trade.</li><li><b>Lead safety:</b> preserve a dependable lead for unknown openers instead of exposing the most fragile damage dealer.</li><li><b>Held-item fit:</b> match survival items to fragile attackers and sustain items to Pokémon expected to remain active.</li><li><b>Consistency:</b> prefer decisions that survive several unknown opponents over one narrow counter.</li></ul><h2>Manual versus Auto</h2><div class="compare"><div><h3>Use Manual when</h3><p>A switch can exploit an immunity, speed order matters, or the active Pokémon cannot damage the target safely.</p></div><div><h3>Use Auto when</h3><p>The matchup is already stable and preserving attention matters more than squeezing out a perfect turn.</p></div></div><h2>A pre-fight community checklist</h2><ol><li>Read the upcoming enemy theme.</li><li>Recount every active trait after a team change.</li><li>Check whether one shared weakness now covers most of the team.</li><li>Move the safest opener into the lead slot.</li><li>Keep enough recovery for the next unknown fight, not only the current one.</li></ol><aside><strong>Verification boundary</strong><p>Reddit advice is treated as strategy input, not an official balance table. Exact stage rewards, unlock requirements, and percentages still require current-build verification.</p></aside></article>
"""
write("/battle-tower/", page("Pokelike Battle Tower Guide — Traits, Teams & Endless Strategy", "Pokelike Battle Tower guide covering endless stages, type traits, manual and auto play, team coverage, and consistent strategy.", "/battle-tower/", tower))

community = """
<section class="article-hero"><nav class="crumb"><a href="/">Home</a> / Community</nav><p class="kicker orange">Source desk</p><h1>Pokelike Reddit<br>Community Guide</h1><p class="lede">The Reddit threads used to find recurring player questions, compare strategies, and identify details that need a current-game retest.</p></section><article class="article"><h2>Where to look first</h2><div class="community-grid"><a href="https://www.reddit.com/r/Pokelike/new/" rel="nofollow noopener"><b>r/Pokelike · New</b><span>Fresh questions, updates, and run discussion ↗</span></a><a href="https://www.reddit.com/r/Pokelike/top/?t=year" rel="nofollow noopener"><b>r/Pokelike · Top this year</b><span>Recurring guides and high-interest discoveries ↗</span></a><a href="https://www.reddit.com/r/Pokesort/new/" rel="nofollow noopener"><b>r/Pokesort · New</b><span>Newest daily hints and spoiler discussions ↗</span></a><a href="https://www.reddit.com/r/Pokelike/comments/1t82gmz/tips_and_tricks/" rel="nofollow noopener"><b>Tips and Tricks</b><span>Strategy thread used in our Traits and Tower guides ↗</span></a></div><h2>How Reddit evidence is used</h2><p>A repeated player question is evidence that a guide is needed. It is not automatically evidence that the most-upvoted answer is mechanically correct. Before a changing claim becomes an unqualified fact, it should be reproduced in the current game build.</p><div class="steps"><div><b>01</b><h3>Discover</h3><p>Record repeated questions, failed runs, unclear tooltips, and conflicting answers.</p></div><div><b>02</b><h3>Cross-check</h3><p>Compare comments with current game behavior and versioned public implementations.</p></div><div><b>03</b><h3>Publish</h3><p>Label the game version, verification date, source, and any remaining uncertainty.</p></div></div><h2>Current community-backed topics</h2><ul><li><b>Pokésort:</b> daily hints, spoilers, and answer sharing.</li><li><b>Traits:</b> same-type breakpoints, shiny contribution, and defensive trade-offs.</li><li><b>Battle Tower:</b> trait planning, held-item choices, and repeatable team strength.</li><li><b>Nuzlocke:</b> risk control and team recommendations that prioritize survival.</li></ul><aside><strong>Editorial rule</strong><p>Reddit wording is summarized, not copied. Community claims that have not been reproduced are labeled as community advice instead of official mechanics.</p></aside></article>
"""
write("/community/", page("Pokelike Reddit Community — Sources, Tips & Research", "Pokelike Reddit source hub for current questions, Pokésort hints, traits, Battle Tower strategy, and transparent community verification.", "/community/", community))

privacy = """
<section class="article-hero"><nav class="crumb"><a href="/">Home</a> / Privacy</nav><p class="kicker orange">Site policy</p><h1>Privacy Policy</h1><p class="lede">A plain-language summary of the data used to operate Pokelike Guide.</p></section><article class="article"><h2>Analytics</h2><p>This site uses Google Analytics to understand aggregate page visits and improve guide coverage. Google may process device, browser, approximate location, and interaction information according to its own policies.</p><h2>Cookies and advertising</h2><p>Analytics and advertising partners may use cookies or similar storage to measure visits, select ads, and prevent fraud. Advertising is not required to access any guide answer or tool.</p><h2>Contact</h2><p>Questions or correction requests can be sent to <a href="mailto:hello@pokelikeguide.cc">hello@pokelikeguide.cc</a>.</p><p><small>Last updated: September 15, 2026.</small></p></article>
"""
write("/privacy/", page("Privacy Policy — Pokelike Guide", "Privacy policy for Pokelike Guide, including analytics, cookies, advertising, and contact information.", "/privacy/", privacy))

urls = ["/", "/pokesort/", "/pokesort/2026-09-15/", "/guides/getting-started/", "/regions/", *(f"/regions/{r[0]}/" for r in regions), "/traits/", "/battle-tower/", "/community/", "/privacy/"]
sitemap = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
for url in urls:
    priority = "1.0" if url == "/" else "0.8"
    sitemap.append(f"  <url><loc>https://pokelikeguide.cc{url}</loc><lastmod>2026-09-15</lastmod><priority>{priority}</priority></url>")
sitemap.append("</urlset>")
(PUBLIC / "sitemap.xml").write_text("\n".join(sitemap) + "\n", encoding="utf-8")
print(f"Generated {len(urls)} pages and sitemap.xml")
