"""Generate the dependency-free Pokelike Guide static site."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "public"
GA_ID = "G-B7HK8JPQPS"

NAV = """
<a href="/pokesort/">Pokesort</a><a href="/regions/">Regions</a><a href="/traits/">Traits</a><a href="/battle-tower/">Battle Tower</a><a href="/guides/getting-started/">Beginner Guide</a>
"""

FOOTER = """
<footer><div class="footer-grid"><div><a class="logo" href="/"><span>PG</span> Pokelike Guide</a><p>Independent, player-made guides for Pokelike.xyz. Facts are checked against playable builds and clearly dated.</p></div><div><strong>Popular</strong><a href="/pokesort/">Pokesort guide</a><a href="/regions/johto/">Johto guide</a><a href="/traits/">All traits</a></div><div><strong>Site</strong><a href="/guides/getting-started/">Getting started</a><a href="/privacy/">Privacy</a><a href="mailto:hello@pokelikeguide.cc">Corrections</a></div></div><div class="legal">© 2026 Pokelike Guide. Unofficial fan resource; not affiliated with Pokelike.xyz, Nintendo, Game Freak, or The Pokémon Company.</div></footer>
"""


def page(title: str, description: str, canonical: str, body: str, *, schema_type: str = "Article") -> str:
    return f"""<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title><meta name="description" content="{description}"><meta name="theme-color" content="#102f28">
<link rel="canonical" href="https://pokelikeguide.cc{canonical}"><meta property="og:type" content="website"><meta property="og:title" content="{title}"><meta property="og:description" content="{description}"><meta property="og:url" content="https://pokelikeguide.cc{canonical}">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Fredoka:wght@500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/styles.css">
<script type="application/ld+json">{{"@context":"https://schema.org","@type":"{schema_type}","headline":"{title}","url":"https://pokelikeguide.cc{canonical}","isPartOf":{{"@type":"WebSite","name":"Pokelike Guide","url":"https://pokelikeguide.cc/"}}}}</script>
<!-- Google tag (gtag.js) --><script async src="https://www.googletagmanager.com/gtag/js?id={GA_ID}"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){{dataLayer.push(arguments)}}gtag('js',new Date());gtag('config','{GA_ID}');</script></head>
<body><header><a class="logo" href="/"><span>PG</span> Pokelike Guide</a><nav>{NAV}</nav><button class="menu" aria-label="Open navigation" aria-expanded="false">Menu</button></header>
<main>{body}</main>{FOOTER}<script src="/script.js"></script></body></html>"""


def write(url: str, html: str) -> None:
    path = PUBLIC / (url.strip("/") or ".") / "index.html"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8")


home = """
<section class="hero"><div><p class="kicker">Independent Pokelike.xyz companion</p><h1>Make every run<br><em>go further.</em></h1><p class="lede">Fast answers for Pokesort, region progression, type traits, and Battle Tower—without burying the useful part.</p><div class="actions"><a class="primary" href="/pokesort/">Open Pokesort guide →</a><a class="secondary" href="/guides/getting-started/">Start a new run</a></div><p class="proof"><b>Current coverage:</b> Kanto through Unova · Normal · Nuzlocke · Battle Tower</p></div><div class="run-card"><div class="run-top"><span>RUN COMPANION</span><b>LIVE GUIDE</b></div><div class="route"><i>●</i><i>?</i><i>⚔</i><i>★</i></div><h2>Choose the smarter path.</h2><p>Check the matchup, understand the trait, and know what comes next before committing to a node.</p><div class="mini-stats"><span><b>5</b> regions</span><span><b>3</b> modes</span><span><b>1</b> clear answer</span></div></div></section>
<section class="signal"><span>Popular player guides</span><a href="/pokesort/">Pokesort guide &amp; hints</a><a href="/regions/johto/">Pokelike Johto guide</a><a href="/traits/">Pokelike traits explained</a></section>
<section class="section"><p class="kicker orange">Daily puzzle</p><div class="split-title"><h2>Looking for today’s<br>Pokesort help?</h2><p>Pokesort has its own daily-puzzle search intent. This guide is specifically for the minigame connected with Pokelike.xyz—not similarly named standalone puzzle sites.</p></div><a class="feature-card daily" href="/pokesort/"><div><span class="badge">DAILY HUB</span><h3>Pokelike Pokesort</h3><p>Hints, solution tracking, puzzle basics, and clearly dated updates in one stable place.</p></div><span class="big-arrow">→</span></a></section>
<section class="section soft"><p class="kicker">Pick a region</p><div class="split-title"><h2>Guides for every<br>campaign.</h2><a class="underlink" href="/regions/">Compare all regions →</a></div><div class="region-grid"><a href="/regions/kanto/"><b>01</b><h3>Kanto</h3><p>Gym route and Elite Four prep.</p></a><a href="/regions/johto/"><b>02</b><h3>Johto</h3><p>Strategy and Lance preparation.</p></a><a href="/regions/hoenn/"><b>03</b><h3>Hoenn</h3><p>Aqua, Magma, Wallace, and Steven.</p></a><a href="/regions/sinnoh/"><b>04</b><h3>Sinnoh</h3><p>Unlock path and Cynthia prep.</p></a><a href="/regions/unova/"><b>05</b><h3>Unova</h3><p>Team Plasma, Ghetsis, and Alder.</p></a></div></section>
<section class="section"><p class="kicker orange">Build with intent</p><div class="split-title"><h2>Understand the systems<br>that decide a run.</h2></div><div class="guide-grid"><a href="/traits/"><span>TYPE SYNERGY</span><h3>Pokelike Traits Explained</h3><p>How same-type team members activate tiered bonuses—and why shiny team members matter in Tower planning.</p><b>Read trait guide →</b></a><a href="/battle-tower/"><span>ENDLESS MODE</span><h3>Battle Tower Guide</h3><p>Understand stages, regional teams, manual versus auto play, and the choices that carry between fights.</p><b>Enter the tower →</b></a><a href="/guides/getting-started/"><span>FIRST RUN</span><h3>Beginner Guide</h3><p>Pick a mode, read the branching map, protect the lead slot, and prepare for eight gyms and the league.</p><b>Start here →</b></a></div></section>
<section class="notice"><div><p class="kicker">Verification policy</p><h2>Useful beats inflated.</h2></div><p>We do not publish guessed daily answers or pretend a community fork is the live game. Every changing fact is dated; uncertain details are labeled and rechecked after updates.</p></section>
"""
write("/", page("Pokelike Guide & Wiki — Pokesort, Traits and Region Guides", "Independent Pokelike.xyz guide with Pokesort help, Kanto through Unova walkthroughs, traits, Battle Tower strategy, and beginner tips.", "/", home, schema_type="WebSite"))

pokesort = """
<section class="article-hero"><nav class="crumb"><a href="/">Home</a> / Pokesort</nav><p class="kicker orange">Community puzzle guide</p><h1>Pokelike Pokesort Guide<br>&amp; Community Hints</h1><p class="lede">A dedicated guide to the Pokesort minigame associated with Pokelike.xyz, with a clear boundary between confirmed community information and an unverified daily board.</p><div class="status"><span>CURRENT DAILY ANSWER</span><b>Not verified for this game day</b><p>There is no answer shown because we cannot confirm the current Pokelike board. This page does not substitute an answer from Pokesort.com, Pokesort.org, or an older Reddit thread.</p></div></section>
<article class="article"><h2>Does Reddit have Pokesort help?</h2><p>Yes. Indexed search results show a Pokelike community thread titled <em>Pokesort tips</em>, older posts titled <em>Let's talk about Pokesort Spoilers</em> and <em>Pokesort Hint 31.07.26</em>, plus a dedicated <strong>r/Pokesort</strong> community described as a place to share answers for the daily minigame on Pokelike.xyz. These results confirm recurring community hints; they do not prove that an old post contains today's board.</p><div class="source-links"><a href="https://www.reddit.com/r/Pokelike/search/?q=pokesort&amp;restrict_sr=1&amp;sort=new" rel="nofollow noopener">Search recent r/Pokelike posts ↗</a><a href="https://www.reddit.com/r/Pokesort/new/" rel="nofollow noopener">Open newest r/Pokesort posts ↗</a></div><h2>A safer solving routine</h2><p>The indexed community advice recommends starting from one relationship you can defend, then testing the whole theory before submitting. Use this checklist rather than committing on the first plausible link:</p><div class="steps"><div><b>01</b><h3>Find a hard relationship</h3><p>Start with a connection supported by a clear game fact, not visual similarity or a guess.</p></div><div><b>02</b><h3>Test both directions</h3><p>Check whether the proposed relationship still makes sense when read from the opposite side.</p></div><div><b>03</b><h3>Validate the leftovers</h3><p>A good partial solution should leave the remaining entries with coherent relationships of their own.</p></div></div><aside><strong>Do not mix up the search results</strong><p>Pokesort.com describes a separate daily Pokémon association puzzle, and Pokesort.org describes a separate 4×4 grouping puzzle. Their answers must not be presented as the Pokelike.xyz minigame answer.</p></aside><h2>What a verified daily answer needs</h2><ul><li>The exact Pokelike game-day date and timezone.</li><li>A screenshot or reproducible board state from Pokelike.xyz.</li><li>Spoiler-free hints followed by an optional answer reveal.</li><li>A verification timestamp and correction history.</li></ul><p>Until all four are available, this remains an evergreen guide and community-source page—not a fake “answer today” page.</p></article>
"""
write("/pokesort/", page("Pokelike Pokesort Guide & Community Hints", "Pokelike Pokesort guide with Reddit community sources, a practical solving checklist, and a clear status for the current daily answer.", "/pokesort/", pokesort))

getting = """
<section class="article-hero"><nav class="crumb"><a href="/">Home</a> / Guides / Getting Started</nav><p class="kicker orange">First run</p><h1>Pokelike Beginner Guide</h1><p class="lede">Pokelike is a browser-based Pokémon roguelike built around irreversible route choices, team management, eight gyms, and a final league.</p></section><article class="article"><h2>The run in one minute</h2><p>Choose a generation, select Normal or Nuzlocke, and pick a starter. Each map is a branching series of reachable nodes. Battles, catches, items, trades, events, Pokémon Centers, and Move Tutors compete for your route; each map ends with a Gym Leader, and the final map leads to the Elite Four and Champion.</p><h2>Normal or Nuzlocke?</h2><div class="compare"><div><h3>Normal</h3><p>Designed for learning. Depending on the chosen wipe rule, a full-team faint can restart the area or end the run.</p></div><div><h3>Nuzlocke</h3><p>Hardcore mode. A fainted team member is normally lost permanently, and a full wipe ends the run.</p></div></div><h2>Five decisions that matter</h2><ol><li><b>Read the next layers.</b> A reachable node closes alternatives on that layer, so look ahead before clicking.</li><li><b>Protect team coverage.</b> Catching raw power is less useful if several members share the same weakness.</li><li><b>Plan healing.</b> A Pokémon Center can restore the team, but the route needed to reach it has an opportunity cost.</li><li><b>Respect speed and immunities.</b> Faster Pokémon act first; an immune target takes no damage from that move type.</li><li><b>Prepare before the boss.</b> Gym and league teams are the tests that determine progression.</li></ol><aside><strong>Version note</strong><p>This overview reflects functionality documented in recent public Pokelike forks. Exact balance values may change in the live build; changing facts are not presented here without a verification date.</p></aside></article>
"""
write("/guides/getting-started/", page("Pokelike Beginner Guide — How to Start and Survive a Run", "A concise Pokelike beginner guide covering modes, branching maps, catches, healing, team coverage, gyms, and Nuzlocke risk.", "/guides/getting-started/", getting))

regions = [
    ("kanto", "Kanto", "Generation I · #001–151", "Eight Kanto Gym Leaders lead into the Kanto Elite Four and Champion.", "Kanto searches specifically include Elite Four, Elite 4 order, E4, tips, and guide intent."),
    ("johto", "Johto", "Generation II · #001–251", "Eight Johto Gym Leaders lead into the Johto Elite Four and Lance.", "Johto has direct guide, strategy, tips, and Reddit search demand."),
    ("hoenn", "Hoenn", "Generation III · #252–386 catchable", "The route features Hoenn leaders, Team Aqua or Team Magma ambushes, the Elite Four, and Champion Steven.", "Hoenn guide and tips appear in current search suggestions."),
    ("sinnoh", "Sinnoh", "Generation IV · #387–493 catchable", "Sinnoh unlocks after a Hoenn win in the documented build and culminates in the Elite Four and Cynthia.", "Sinnoh Tower and Reddit queries appear in current search suggestions."),
    ("unova", "Unova", "Generation V · #494–649 catchable", "Unova unlocks after a Sinnoh win in the documented build and includes Team Plasma encounters before Alder's league.", "Unova, Unova Battle Tower, and Unova Reddit are established search suggestions."),
]
cards = "".join(f'<a href="/regions/{slug}/"><b>{label}</b><span>{subtitle}</span><p>{summary}</p></a>' for slug,label,subtitle,summary,_ in regions)
hub = f'<section class="article-hero"><nav class="crumb"><a href="/">Home</a> / Regions</nav><p class="kicker orange">Campaign routes</p><h1>Pokelike Region Guides</h1><p class="lede">Choose a generation and prepare for its gym route, rival encounters, league, and unlock path.</p></section><section class="section"><div class="region-list">{cards}</div></section>'
write("/regions/", page("Pokelike Region Guides — Kanto, Johto, Hoenn, Sinnoh & Unova", "Pokelike region guide hub for Kanto, Johto, Hoenn, Sinnoh, and Unova campaigns, including progression and league preparation.", "/regions/", hub))
for slug, label, subtitle, summary, demand in regions:
    body = f'<section class="article-hero"><nav class="crumb"><a href="/">Home</a> / <a href="/regions/">Regions</a> / {label}</nav><p class="kicker orange">{subtitle}</p><h1>Pokelike {label} Guide</h1><p class="lede">{summary}</p></section><article class="article"><h2>What this campaign includes</h2><p>{summary} The run uses the same core branching-map decisions: decide between battles, catches, items, trades, events, healing, and move improvements before committing to a path.</p><h2>Search demand for this guide</h2><p>{demand} This page consolidates that intent rather than creating several short, overlapping pages.</p><h2>Preparation checklist</h2><ul><li>Cover the major type weaknesses represented by your current route and upcoming boss.</li><li>Keep the lead slot healthy and review speed before entering a mandatory fight.</li><li>Use healing and Move Tutor opportunities before the league rather than carrying unused resources.</li><li>Check the current game version before relying on fixed balance or encounter data.</li></ul><aside><strong>Accuracy status</strong><p>Campaign structure is based on recent public rule implementations. Exact teams, levels, and rewards require live-build verification before publication and are intentionally not invented here.</p></aside></article>'
    write(f"/regions/{slug}/", page(f"Pokelike {label} Guide — Strategy, Progression & League", f"Pokelike {label} guide covering campaign progression, route planning, team preparation, and the {label} league.", f"/regions/{slug}/", body))

traits = """
<section class="article-hero"><nav class="crumb"><a href="/">Home</a> / Traits</nav><p class="kicker orange">Team synergy</p><h1>Pokelike Traits Explained</h1><p class="lede">Type traits are a core Battle Tower system: stacking same-type team members unlocks tiered bonuses, while shiny members contribute additional trait value.</p></section><article class="article"><h2>How traits affect team building</h2><p>A trait changes the value of team composition. Instead of choosing six individually strong Pokémon, Tower planning asks whether shared types activate a bonus that offsets duplicated weaknesses.</p><div class="steps"><div><b>01</b><h3>Count shared types</h3><p>Dual-type team members can contribute to more than one type plan.</p></div><div><b>02</b><h3>Check the next threshold</h3><p>A replacement is valuable when it activates a stronger trait tier without opening a dangerous weakness.</p></div><div><b>03</b><h3>Recheck coverage</h3><p>A trait bonus does not remove the need for offensive coverage, speed, or safe switching.</p></div></div><h2>Why this page does not publish guessed values</h2><p>Search demand exists for “Pokelike traits,” “traits explained,” “best traits,” and “all traits.” Exact effect values are more likely to change than the underlying concept, so a numerical compendium will be published only from a versioned dataset.</p><aside><strong>Next data release</strong><p>The planned filter will compare all documented traits by effect, tier threshold, team role, and verified game version.</p></aside></article>
"""
write("/traits/", page("Pokelike Traits Explained — Type Synergy & Best Team Planning", "Understand Pokelike traits, type stacking, shiny trait value, tier thresholds, and Battle Tower team synergy.", "/traits/", traits))

tower = """
<section class="article-hero"><nav class="crumb"><a href="/">Home</a> / Battle Tower</nav><p class="kicker orange">Endless challenge</p><h1>Pokelike Battle Tower Guide</h1><p class="lede">Battle Tower is a separate endless challenge built around stages, regional opponents, team management, type traits, and score.</p></section><article class="article"><h2>What is different in the Tower?</h2><p>Public rule implementations describe a stage-based mode that can be played manually or resolved automatically. Type traits remain active, opponent themes change by region, and progression is measured by how deep the run reaches.</p><h2>Build around repeatable strength</h2><ul><li><b>Coverage:</b> avoid a team that folds to one common attacking type.</li><li><b>Trait efficiency:</b> compare the next trait tier with the weaknesses created by stacking a type.</li><li><b>Lead safety:</b> the first matchup matters when battles arrive repeatedly.</li><li><b>Consistency:</b> prefer decisions that survive several unknown opponents over one narrow counter.</li></ul><h2>Manual versus Auto</h2><div class="compare"><div><h3>Manual</h3><p>Best when switching, immunities, speed, and move choice can materially improve survival.</p></div><div><h3>Auto</h3><p>Useful for lower-risk stretches, but a convenient setting is not automatically the strongest strategy.</p></div></div><aside><strong>Verification boundary</strong><p>Exact stage rewards, unlock requirements, and balance values are deliberately omitted until they can be checked against the live build.</p></aside></article>
"""
write("/battle-tower/", page("Pokelike Battle Tower Guide — Traits, Teams & Endless Strategy", "Pokelike Battle Tower guide covering endless stages, type traits, manual and auto play, team coverage, and consistent strategy.", "/battle-tower/", tower))

privacy = """
<section class="article-hero"><nav class="crumb"><a href="/">Home</a> / Privacy</nav><p class="kicker orange">Site policy</p><h1>Privacy Policy</h1><p class="lede">A plain-language summary of the data used to operate Pokelike Guide.</p></section><article class="article"><h2>Analytics</h2><p>This site uses Google Analytics to understand aggregate page visits and improve guide coverage. Google may process device, browser, approximate location, and interaction information according to its own policies.</p><h2>Cookies and advertising</h2><p>Analytics or future advertising partners may use cookies or similar storage. Advertising is not currently required to access any guide answer or tool.</p><h2>Contact</h2><p>Questions or correction requests can be sent to <a href="mailto:hello@pokelikeguide.cc">hello@pokelikeguide.cc</a>.</p><p><small>Last updated: September 14, 2026.</small></p></article>
"""
write("/privacy/", page("Privacy Policy — Pokelike Guide", "Privacy policy for Pokelike Guide, including analytics, cookies, advertising, and contact information.", "/privacy/", privacy))

urls = ["/", "/pokesort/", "/guides/getting-started/", "/regions/", *(f"/regions/{r[0]}/" for r in regions), "/traits/", "/battle-tower/", "/privacy/"]
sitemap = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
for url in urls:
    priority = "1.0" if url == "/" else "0.8"
    sitemap.append(f"  <url><loc>https://pokelikeguide.cc{url}</loc><lastmod>2026-09-14</lastmod><priority>{priority}</priority></url>")
sitemap.append("</urlset>")
(PUBLIC / "sitemap.xml").write_text("\n".join(sitemap) + "\n", encoding="utf-8")
print(f"Generated {len(urls)} pages and sitemap.xml")
